---
- hosts: ubuntu
  become: yes
  tasks:
  - name: Install Zabbix Agent
    apt:
      deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

  - name: Copy Filebeat .deb
    copy:
      src: /etc/ansible/package/filebeat-8.7.0-amd64.deb
      dest: /home/filebeat-8.7.0-amd64.deb

  - name: Install Filebeat
    apt:
      deb: /home/filebeat-8.7.0-amd64.deb   

  - name: Update all package
    apt:
      update_cache: yes 

  - name: Install package
    apt:
      pkg:
      - nginx
      - apache2
      - php
      - libapache2-mod-php
      - zabbix-agent
      - bind9
      - bind9utils
      - bind9-doc
      - postfix

- hosts: centos
  become: yes
  tasks:
  - name: Copy ElasticSearch
    copy:
      src: /etc/ansible/package/elasticsearch-8.7.0-x86_64.rpm
      dest: /home/elasticsearch-8.7.0-x86_64.rpm

  - name: Copy Kibana
    copy:
      src: /etc/ansible/package/kibana-8.7.0-x86_64.rpm
      dest: /home/kibana-8.7.0-x86_64.rpm

  - name: Copy Logstash
    copy:
      src: /etc/ansible/package/logstash-8.7.0-x86_64.rpm
      dest: /home/logstash-8.7.0-x86_64.rpm

  - name: Copy Filebeat
    copy:
      src: /etc/ansible/package/filebeat-8.7.0-x86_64.rpm
      dest: /home/filebeat-8.7.0-x86_64.rpm      

  - name: Install Zabbix Agent rpm
    yum:
      name: https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-release-6.4-1.el7.noarch.rpm
      state: present

  - name: Install Postgres rpm
    yum:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: present    

  - name: Update all package and install
    yum:
      update_cache: true
      name:
        - zabbix-agent
        - epel-release
        - yum-utils
        - postgresql12-server
        - postgresql12
        - java    

  - name: Install Elasticsearch
    yum:
      name: /home/elasticsearch-8.7.0-x86_64.rpm
      state: present

  - name: Install Kibana
    yum:
      name: /home/kibana-8.7.0-x86_64.rpm
      state: present

  - name: Install Logstash
    yum:
      name: /home/logstash-8.7.0-x86_64.rpm
      state: present

  - name: Install Filebeat
    yum:
      name: /home/filebeat-8.7.0-x86_64.rpm
      state: present
